use_frameworks!

platform :ios, '15.0'

target 'PaywallViewController' do
  pod 'IQPaywallUI', :git => 'https://github.com/hackiftekhar/IQPaywallUI.git', :branch => 'main'
  pod 'IQStoreKitManager', :path => '../'

  pod "SwiftLint"
end

